---
# Using Debian Bookworm base for glibc compatibility
# (opencode-ai ships pre-compiled native binaries that require glibc)
# Includes: S6-Overlay, Bashio, TempIO
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  # Build arguments if needed
  BUILD_DATE: ""
labels:
  org.opencontainers.image.title: "HA OpenCode"
  org.opencontainers.image.description: "AI coding agent for Home Assistant"
  org.opencontainers.image.source: "https://github.com/magnusoverli/ha_opencode"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.vendor: "Magnus Overli"
